### ISSUE TITLE
Doesn't work with Docker Beta

### ISSUE THREAD

**Issue by IAPOLINARIO** [docker/dockercraft#62]
I'm using Docker Beta for Mac and can not make the game find the dockercraft server. The container starts normally, but when I try to add a new server, the game can not find to connect.

**Comment by JBYoshi** [comment]
I think the issue is that because Docker runs Linux on a virtual machine and doesn't automatically set up port forwarding. First, when running `docker create` or `docker run`, add the argument `-p 25565:25565`. This will expose the port. Then, if you're running the game on the same Mac as Docker, type `docker-machine ip` into a Docker terminal and connect to that IP address.

If you're running them on different systems, open VirtualBox, select your Docker VM, and click Settings. Under Network, click Port Forwarding, then add an entry with host port 25565 and guest port 25565. Then you can connect to Dockercraft using the IP of the server machine.

**Comment by IAPOLINARIO** [comment]
The ports exposure are working, because I have other containers running and I can access them normally (Jenkins, for example). Anyway, I ran the docker run with the -p argument, and even then, the game could not find the server.

Docker Beta does not use the docker machine, maybe this can interfere in any way.

**Comment by IAPOLINARIO** [comment]
I just realized that the problem isn't with the version of the Docker, but with the version of Minecraft. As mentioned in another issue, the 1.9 version of Minecraft doesn't work with dockercraft. I changed to 1.8 and everything worked perfectly!

**Comment by gdevillele** [comment]
Good 👍
We are going to add Minecraft 1.9 support soon. Sorry for the delay.

**Comment by IAPOLINARIO** [comment]
Well, at least now we know that works with Docker Beta! :)

**Comment by gdevillele** [comment]
Yes it does.
Dockercraft is developed using Docker for Mac 😉
