### ISSUE TITLE
Cubrite vendoring and update

### ISSUE THREAD

**Issue by gdevillele** [docker/dockercraft#71]
per @ricardotk 's suggestion in #70 :
- consider vendoring Cubrite (and plugins) using submodules.
- also, update Cubrite to the latest version

**Comment by dave-tucker** [comment]
Submodules are awful.

I discussed with @aduermael about pinning the Cuberite version in our Dockerfile - which I think is a decent solution. We want to have control over which version of Cuberite we're vendoring.

As for plugins, I think we need a better way of managing them rather than checking them in to the repo. Ideally...

I think the right way to do this is to handle the world creation in the Dockerfile and add the `Docker` plugin to that world + making sure the world is empty etc...
This is more work for us, but it cleanly separates our code from Cuberite code.

**Comment by dave-tucker** [comment]
> but for third party libraries and plugins that we won't change I think its a decent solution too.

If we really have to do it, I'd suggest we do a subtree merge instead.

> Well, we can still pin the version and use submodules (tags)

Agreed, but submodules don't give us a binary distribution which we have today in the Dockerfile. Thats bad, as we then have to bloat our image with all of the cruft required to build Cuberite.

I guess my point is that the files from Cuberite that we don't change (e.g plugins and world related things) have no place in being checked in to the repo at all either directly (like today) or as a submodule or a subtree merge.

I should have some time next week and I plan to see if we can remove the files from the repo completely and do all of the world assembly in the Dockerfile itself.

**Comment by ricardotk** [comment]
> I guess my point is that the files from Cuberite that we don't change (e.g plugins and world related things) have no place in being checked in to the repo at all either directly (like today) or as a submodule or a subtree merge.

I agree

> I should have some time next week and I plan to see if we can remove the files from the repo completely and do all of the world assembly in the Dockerfile itself.

That would be great :smile:
