### ISSUE TITLE
Can I run command directly into it?

### ISSUE THREAD

**Issue by wiput1999** [docker/dockercraft#82]
I want dockercraft can be run command directly into minecraft server from
`docker exec`
I want to use it with docker SDKs

Thanks,
Wiput Pootong

**Comment by willysunny** [comment]
pretty sure you can if you combine dockercraft with minecraft docker

since then the newly created minecraft server would be a docker container, which then you should be able to send commands directly into it

but do not expect things like `exec -i` to work though, as the chat is not able to handle interactive hooks
